GRANT SELECT ON TWGBWSES TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT EXECUTE ON f_format_name TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sgbstdn TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON goremal TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sgradvr TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;


 
GRANT SELECT ON sprtele TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON stvstst TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT SELECT ON gurassl TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON spraddr TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON utr_curr_acct_pers_assoc TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON utb_account TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON utb_system TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON szbisud TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON szvadm1_mv TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
--does not exist in DEVL
GRANT SELECT ON szvgrd1_mv TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT EXECUTE ON fz_get_rh_lo_address_rowid TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON baninst1.FZ_RPT_CRNT_ADDR TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON FZ_GET_EMAIL_TYPE_ROWID TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON F_FORMAT_NAME TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;


GRANT EXECUTE ON F_ORGN_TITLE TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
--COURSE DOMAIN
GRANT SELECT ON szvdist TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON ssbsect TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sirasgn TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON stvschd TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sfrstcr TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON stvrsts TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
--Admission and Registration Domains

GRANT EXECUTE ON BANINST1.fz_reg_elig TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
--.f_get_desc

GRANT EXECUTE ON BANINST1.GOKODSF TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON calc_classification TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON f_astd_end_of_term TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT SELECT ON shrlgpa TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sprhold TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON stvhldd TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON szvgrd1 TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON stvstyp TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON tbraccd TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON sfrctrl TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT SELECT ON szvterm TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT EXECUTE ON f_get_current_term TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;
GRANT INSERT, UPDATE, DELETE, SELECT ON dirxml.eventlog TO ban_default_pagebuilder_m;
COMMIT;
GRANT SELECT ON dirxml.seq_recid TO ban_default_pagebuilder_m;
COMMIT;

GRANT SELECT ON gobtpacv TO ban_default_pagebuilder_m;
COMMIT;

GRANT SELECT ON szvgrd1_mv TO BAN_DEFAULT_PAGEBUILDER_M;
COMMIT;

GRANT EXECUTE ON BWZKAFIL TO ban_default_pagebuilder_m;
COMMIT;


GRANT EXECUTE ON F_STUDENT_GEN_STUDENTS_IND TO ban_default_pagebuilder_m;
COMMIT;


GRANT EXECUTE ON FZ_RPT_CRNT_PHONE TO ban_default_pagebuilder_m;
COMMIT;

GRANT EXECUTE ON fz_rpt_crnt_emal TO ban_default_pagebuilder_m;
COMMIT;
